projects:
  - name: AutoGPT
    changed_files:
      - glob: "autogpts/autogpt/**"

  - name: Forge
    changed_files:
      - glob: "autogpts/forge/**"

  - name: Benchmark
    changed_files:
      - glob: "benchmark/**"

  - name: Frontend
    changed_files:
      - glob: "frontend/**"

  - name: Arena
    changed_files:
      - glob: "arena/**"

  - name: Documentation
    changed_files:
      - glob: "docs/**"
