# To boot the app run the following:
# docker-compose up

version: '3.9'

services:
  auto-gpt:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ../
    tty: true
    stdin_open: true #
