#!/bin/bash

# Define variables
script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
repo="https://github.com/polywrap/evo.ninja.git"
branch="release/autogpt"

# Clone the repo and checkout the release branch
echo "Cloning evo.ninja..."
git clone --depth 1 --branch $branch $repo || {
    echo "Cloning failed, trying without --depth 1..."
    git clone $repo || {
        echo "Cloning failed, please check the repository URL."
        exit 1
    }
}
cd evo.ninja || {
    echo "Failed to change directory to cloned repo."
    exit 1
}

echo "Setup successfully."
