# The name and URL of the website.
site_name: AutoGPT Documentation
site_url: https://docs.agpt.co/

# The URL of the repository where the source code of the project is hosted.
repo_url: https://github.com/Significant-Gravitas/AutoGPT

# The directory where the documentation files are located.
docs_dir: content

# The navigation structure of the website, including sections and pages.
nav:
  # A section for the AutoGPT Agent.
  - AutoGPT Agent:
      # The introduction page for the AutoGPT Agent.
      Introduction: AutoGPT/index.md
      # A subsection for setup instructions.
      Setup:
        # The main setup page for AutoGPT.
        - Setting up AutoGPT: AutoGPT/setup/index.md
        # A page for setting up AutoGPT with Docker.
        - Set up with Docker: AutoGPT/setup/docker.md
      # A page for usage instructions.
      Usage: AutoGPT/usage.md
      # A page for plugins.
      Plugins: AutoGPT/plugins.md
      # A subsection for configuration options.
      # Configuration:
      #   - Options: AutoGPT/configuration/options.md
      #   - Search: AutoGPT/configuration/search.md
      #   - Memory: AutoGPT/configuration/memory.md
      #   - Voice: AutoGPT/configuration/voice.md
      #   - Image Generation: AutoGPT/configuration/imagegen.md
      # A subsection for contributing to the project.
      - Help us improve AutoGPT:
          # A page for sharing debug logs.
          - Share your debug logs with us: AutoGPT/share-your-logs.md
          # A page for the contribution guide.
          - Contribution guide: contributing.md
          # A page for running tests.
          - Running tests: AutoGPT/testing.md
          # A page for the code of conduct.
          - Code of Conduct: code-of-conduct.md

# The theme and color scheme of the website, as well as various features.
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/book-open-variant
  favicon: favicon.png
  features:
    # Enable navigation sections.
    - navigation.sections
    # Enable table of contents following the reader.
    - toc.follow
    # Enable a navigation bar at the top of the page.
    - navigation.top
    # Enable copying code from code blocks.
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# A list of Markdown extensions and plugins used to enhance the functionality of the Markdown parser.
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# A list of additional plugins for the documentation website.
plugins:
  - table-reader
  - search

# A list of additional JavaScript files to be included in the website.
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - _javascript/tablesort.js
  - _javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-m
