coverage:
  status:
    project:
      default:
        target:
          auto: 1%
        informational: true
    patch:
      default:
        target: 80%
        carryforward: true

  ## Add this section once you've separated your coverage uploads for unit and integration tests
  flags:
    unit-tests:
      carryforward: true
    integration-tests:
      carryforward: true
